In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

In [3]:
dirname = '/content/drive/MyDrive/Colab_Notebooks/Thesis/'
raw_data = pd.read_csv(dirname + 'Speed_Dating_Data.csv', encoding= 'unicode_escape')

In [4]:
 # remove features already have a coded version in the dataset
noncodeFeatures = ['career','field', 'zipcode','race','race_o']
 # remove features got after candidates meeting each other
unrelatedPreeventSurvey = ['condtn','tuition','mn_sat','pf_o_sha','shar1_1','imprelig', 'int_corr', 'pf_o_att'
                           ,'imprelig','pf_o_sin','pf_o_int','pf_o_fun','pf_o_amb'
                           ,'goal','date','go_out','exphappy','expnum'
                           ,'attr1_1','sinc1_1','intel1_1','fun1_1','amb1_1','shar1_1'
                           ,'attr2_1','sinc2_1','intel2_1','fun2_1','amb2_1','shar2_1'
                           ,'attr4_1','sinc4_1','intel4_1','fun4_1','amb4_1','shar4_1'
                           ,'attr5_1','sinc5_1','intel5_1','fun5_1','amb5_1','shar5_1']
afterEventSurvey = ['attr_o', 'sinc_o','intel_o','fun_o','amb_o','shar_o','like_o','prob_o'
                    ,'met_o', 'attr', 'sinc','intel','fun','amb','shar','like','prob','met','match_es'
                    ,'attr1_s', 'sinc1_s','intel1_s','fun1_s','amb1_s','shar1_s','attr3_s','sinc3_s','intel3_s','fun3_s','amb3_s']
followUp1Features = ['satis_2', 'length', 'numdat_2', 'attr7_2', 'sinc7_2', 'intel7_2', 'fun7_2', 'amb7_2'
                    ,'shar7_2', 'attr1_2', 'sinc1_2', 'intel1_2', 'fun1_2', 'amb1_2', 'shar1_2', 'attr4_2'
                    ,'sinc4_2', 'intel4_2', 'fun4_2', 'amb4_2', 'shar4_2', 'attr2_2', 'sinc2_2', 'intel2_2'
                    ,'fun2_2', 'amb2_2', 'shar2_2', 'attr3_2', 'sinc3_2', 'intel3_2', 'fun3_2', 'amb3_2'
                    ,'attr5_2', 'sinc5_2', 'intel5_2', 'fun5_2', 'amb5_2']
matchResult = ['match']
followUp2Features = ['you_call', 'them_cal', 'date_3', 'numdat_3', 'num_in_3', 'attr1_3'
                    ,'sinc1_3', 'intel1_3', 'fun1_3', 'amb1_3', 'shar1_3', 'attr7_3','sinc7_3', 'intel7_3', 'fun7_3'
                    ,'amb7_3', 'shar7_3', 'attr4_3', 'sinc4_3', 'intel4_3', 'fun4_3', 'amb4_3', 'shar4_3', 'attr2_3'
                    ,'sinc2_3', 'intel2_3', 'fun2_3', 'amb2_3', 'shar2_3', 'attr3_3', 'sinc3_3', 'intel3_3', 'fun3_3'
                    ,'amb3_3', 'attr5_3', 'sinc5_3', 'intel5_3', 'fun5_3', 'amb5_3']
# remove features set for conducting the event
eventFeatures = ['idg','round','position','positin1','order','match_es','id','wave','partner']
cleanedData_01 = raw_data.loc[:,~raw_data.columns.isin(unrelatedPreeventSurvey + afterEventSurvey + followUp1Features + followUp2Features + eventFeatures + noncodeFeatures)]

In [5]:
numeric_features = cleanedData_01.select_dtypes(include='number').columns.tolist()
object_features = cleanedData_01.select_dtypes(include='object').columns.tolist()
boolean_features = cleanedData_01.select_dtypes(include='bool').columns.tolist()
object_features

['undergra', 'from', 'income']

In [6]:
def typeChange (column):
    if cleanedData_01[column].dtype == 'object':
        cleanedData_01[column] = cleanedData_01[column].str.replace(',', '').astype(float)
    else: cleanedData_01[column] = cleanedData_01[column].astype(float)
object_transfer_feature = ['income']
for i in (object_transfer_feature + boolean_features):
    typeChange(i)

floar_transfer_feature = ['field_cd','career_c']
for i in floar_transfer_feature:
    # Fill missing values with 0
    cleanedData_01[i].fillna(-1, inplace=True)
    # Convert to integer
    cleanedData_01[i] = cleanedData_01[i].astype(int)

<ipython-input-6-2b505789368a>:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanedData_01[column] = cleanedData_01[column].str.replace(',', '').astype(float)
<ipython-input-6-2b505789368a>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanedData_01[i].fillna(-1, inplace=True)
<ipython-input-6-2b505789368a>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanedData_01[i] = cleanedData_01[i].astype(int)
<ipython-input-6-2b505789368a>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanedData_01[i].fillna(-1, inplace=True)
<ipython-input-6-2b505789368a>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleanedData_01[i] = cleanedData_01[i].astype(int)

In [7]:
cleanedData_01.info(verbose = True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Data columns (total 37 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   iid       8378 non-null   int64
 1   gender    8378 non-null   int64
 2   pid       8368 non-null   float64
 3   match     8378 non-null   int64
 4   samerace  8378 non-null   int64
 5   age_o     8274 non-null   float64
 6   dec_o     8378 non-null   int64
 7   age       8283 non-null   float64
 8   field_cd  8378 non-null   int64
 9   undergra  4914 non-null   object
 10  imprace   8299 non-null   float64
 11  from      8299 non-null   object
 12  income    4279 non-null   float64
 13  career_c  8378 non-null   int64
 14  sports    8299 non-null   float64
 15  tvsports  8299 non-null   float64
 16  exercise  8299 non-null   float64
 17  dining    8299 non-null   float64
 18  museums   8299 non-null   float64
 19  art       8299 non-null   float64
 20  hiking    8299 non-null   float64
 21  gaming    8299 non-null   float64
 22  clubbing  8299 non-null   float64
 23  reading   8299 non-null   float64
 24  tv        8299 non-null   float64
 25  theater   8299 non-null   float64
 26  movies    8299 non-null   float64
 27  concerts  8299 non-null   float64
 28  music     8299 non-null   float64
 29  shopping  8299 non-null   float64
 30  yoga      8299 non-null   float64
 31  attr3_1   8273 non-null   float64
 32  sinc3_1   8273 non-null   float64
 33  fun3_1    8273 non-null   float64
 34  intel3_1  8273 non-null   float64
 35  amb3_1    8273 non-null   float64
 36  dec       8378 non-null   int64
dtypes: float64(27), int64(8), object(2)
memory usage: 2.4+ MB

In [ ]:
cleanedData_01.to_csv(dirname + 'cleanedData_01.csv', index=False)

In [ ]:
cleanedData_01.head()

,iid,gender,pid,match,samerace,age_o,age,field_cd,undergra,imprace,...,movies,concerts,music,shopping,yoga,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1
0,1,0,11.0,0,0,27.0,21.0,1,NaN,2.0,...,10.0,10.0,9.0,8.0,1.0,6.0,8.0,8.0,8.0,7.0
1,1,0,12.0,0,0,22.0,21.0,1,NaN,2.0,...,10.0,10.0,9.0,8.0,1.0,6.0,8.0,8.0,8.0,7.0
2,1,0,13.0,1,1,22.0,21.0,1,NaN,2.0,...,10.0,10.0,9.0,8.0,1.0,6.0,8.0,8.0,8.0,7.0
3,1,0,14.0,1,0,23.0,21.0,1,NaN,2.0,...,10.0,10.0,9.0,8.0,1.0,6.0,8.0,8.0,8.0,7.0
4,1,0,15.0,1,0,24.0,21.0,1,NaN,2.0,...,10.0,10.0,9.0,8.0,1.0,6.0,8.0,8.0,8.0,7.0